---
- hosts: test
  become: True
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Install python pip
      package:
        name: python3-pip
        state: present
        update_cache: true
    - name: Install docker
      apt:
        name: docker
        state: present
    - name: start docker
      service:
        name: docker
        state: started
        enabled: yes
    - name: Install docker-py python module
      pip:
        name: docker-py
        state: present
    - name: Start the container
      docker_container:
        name: anuapp
        image: "anudevops09/anuapp18:$BUILD_NUMBER"
        state: started
        ports:
        - "8080:80"
        tty: true
        detach: true
   - name: reload systemd daemon
     command: systemctl daemon-reload
