---
- hosts: test
  environment:
    PYTHONPATH: "{{ lookup('env','PYTHONPATH') }}:/usr/local/lib/python2.7/dist-packages:/usr/local/lib/python2.7/site-packages"
  become: True
  tasks:
    - name: Install python pip
      package:
        name: "python3-pip"
        state: present
        update_cache: true
    - name: Install docker
      apt:
        name: docker
        state: present
    - name: start docker
      service:
        name: docker
        state: started
        enabled: yes
    - name: Install docker-py python module
      pip:
        name: docker-py
        state: present
    - name: Start the container
      docker_container:
        name: anuapp
        image: "anudevops09/anuapp:$BUILD_NUMBER"
        state: started
        published_ports:
          - 0.0.0.0:8090:8090
